version: '3.8'
services:
  aggregator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      DEDUP_DB: "/app/data/dedup_store.db"
  publisher:
    build: ./publisher
    depends_on:
      - aggregator
    environment:
      AGGREGATOR_URL: "http://aggregator:8080"
    # default command is defined in publisher/Dockerfile
